#ifndef HEADER_H
#define HEADER_H

// Error codes
#define ERROR_NO_LIBS 2
#define ERROR_LIB_NOT_FOUND 3
#define ERROR_LIB_IS_INVALID 4
#define ERROR_LIB_CHARSIZE_INVALID 5
#define CURRENT_API_VERSION 0x010000
#endif // HEADER_H

